# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: BlackFishBlog
subtitle: ''
description: ''
keywords:
author: Alex
language: zh-CN
timezone: ''

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://pj3691.github.io/
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

#douban
douban:
  id: 210807073
  builtin: false
  item_per_page: 10
  meta_max_line: 4
  customize_layout: page
  book:
    path: books/index.html
    title: '读书'
    quote: '我需要三件东西：爱情、友谊和图书。然而这三者之间何其相通！炽热的爱情可以充实图书的内容，图书又是人们最忠实的朋友'
    option:
      aside: false # 关闭侧边栏
      comments: true # 关闭评论
      top_img: false
  movie:
    path: movies/index.html
    title: '电影'
    quote: '生活不是电影，生活比电影苦。'
    option:
      aside: false # 关闭侧边栏
      comments: true # 关闭评论
      top_img: false
  game:
    path: games/index.html
    title: '游戏'
    quote: '第九艺术'
    option:      
      aside: false # 关闭侧边栏
      comments: true # 关闭评论
      top_img: false
  song:
    path: songs/index.html
    title: '歌'
    quote: '不觉碧山暮，秋云暗几重'
    option:
      aside: false # 关闭侧边栏
      comments: true # 关闭评论
      top_img: false
  timeout: 1000000

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: butterfly
plugins:
  - hexo-algoliasearch

# Easy images
easy_images:
  init: false # 默认 false；改为 true，将处理过去所有 post，通常装插件后第一次运行时使用。
  cdn_prefix: http://yourcdn.com # 默认 null; 图片前缀，在生成 html 文件时为 image 添加前缀
  max_width: 800 # 默认 null；设置图片最大宽度
  max_height: 800 # 默认 null；设置图片最大高度

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repo: 'https://github.com/pj3691/pj3691.github.io.git'
  branch: master

#algolia settings
algolia :
  appId : 'DXGQXA55WY'
  apiKey : '7dfc2173017041a54101c856c2648727'
  indexName : '2222'
  chunkSize : 5000
  fields: 
    - path
    - title
    - content:strip

aplayer:
  meting: true
  asset_inject: false